[mypy]
ignore_missing_imports = True
disable_error_code = assignment, arg-type, call-arg, union-attr, var-annotated, return-value, operator, attr-defined, dict-item, index, misc, call-overload, name-defined, annotation-unchecked, return
exclude = (?i)(brain|gemini|scratch|scripts)
