[lint]
ignore = [
    "E402", # Module level import not at top of file (common in scripts)
    "E711", # Comparison to None should be 'cond is not None' (SQLAlchemy)
    "E712", # Avoid equality comparisons to True (SQLAlchemy)
    "E722", # Do not use bare `except` (common in scripts/tests)
    "F401", # Imported but unused (common in __init__.py for exposing)
    "E701", # Multiple statements on one line (colon)
    "F841", # Local variable is assigned to but never used
    "E702", # Multiple statements on one line (semicolon)
]
