const fs = require('fs');
const path = require('path');

const DIRECTORIES = [
  path.join(__dirname, '../src/widgets'),
  path.join(__dirname, '../src/features'),
  path.join(__dirname, '../src/shared/ui')
];

// Mappings for replacements
const replacements = [
  // Text colors
  { regex: /\btext-(?:gray|slate)-(?:900|800|700)\b/g, replace: 'text-foreground' },
  { regex: /\btext-(?:gray|slate)-(?:600|500|400)\b/g, replace: 'text-muted-foreground' },
  { regex: /\bdark:text-(?:white|gray-100|slate-100)\b/g, replace: '' },
  
  // Background colors
  { regex: /\bbg-(?:gray|slate)-(?:50|100|200)\b/g, replace: 'bg-muted' },
  { regex: /\bdark:bg-(?:slate|gray)-(?:800|900|950)\b/g, replace: '' },
  { regex: /\bbg-white\b/g, replace: 'bg-card' },
  { regex: /\bbg-slate-900\b/g, replace: 'bg-card' }, // Many times slate-900 is hardcoded for cards

  // Border colors
  { regex: /\bborder-(?:gray|slate)-(?:100|200|300)\b/g, replace: 'border-border' },
  { regex: /\bdark:border-(?:slate|gray)-(?:700|800)\b/g, replace: '' }
];

function processFile(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');
  let originalContent = content;

  replacements.forEach(({ regex, replace }) => {
    content = content.replace(regex, replace);
  });

  // Cleanup multiple spaces generated by removing dark: classes
  content = content.replace(/\s{2,}/g, ' ');
  content = content.replace(/" /g, '"');
  content = content.replace(/ "/g, '"');
  content = content.replace(/' /g, "'");
  content = content.replace(/ '/g, "'");
  content = content.replace(/` /g, '`');
  content = content.replace(/ `/g, '`');

  if (content !== originalContent) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`Updated: ${filePath}`);
    return true;
  }
  return false;
}

function walkDir(dir) {
  if (!fs.existsSync(dir)) return;
  
  const files = fs.readdirSync(dir);
  let updatedCount = 0;

  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);

    if (stat.isDirectory()) {
      updatedCount += walkDir(filePath);
    } else if (file.endsWith('.tsx') || file.endsWith('.ts')) {
      if (processFile(filePath)) {
        updatedCount++;
      }
    }
  });

  return updatedCount;
}

let totalUpdated = 0;
DIRECTORIES.forEach(dir => {
  totalUpdated += walkDir(dir);
});

console.log(`\nRefactoring complete. Total files updated: ${totalUpdated}`);
