"""Add knowledge base models

Revision ID: 0002994e6a99
Revises: e8c2a41f9b77
Create Date: 2026-05-09 11:17:07.042475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002994e6a99'
down_revision = 'e8c2a41f9b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_alerts', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_animal_alerts_field_id', 'fields', ['field_id'], ['id'])

    with op.batch_alter_table('animal_groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('qr_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_animals_qr_code', ['qr_code'])

    with op.batch_alter_table('attachment_blobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_attachment_blobs_attachment_id', ['attachment_id'])

    with op.batch_alter_table('community_nodes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_community_nodes_node_id', ['node_id'])

    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'REVOKED', 'LOST', name='devicestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))

    with op.batch_alter_table('farm_expenses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('infrastructure', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TANQUE', 'CERCA', 'MAQUINARIA', 'CORRAL', 'BEBEDERO', name='infrastructuretype'),
               existing_nullable=False)

    with op.batch_alter_table('node_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CHAT', 'ALERT', 'SYSTEM', name='nodemessagetype'),
               existing_nullable=False,
               existing_server_default=sa.text("'CHAT'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'DELIVERED', 'READ', name='nodemessagestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.create_unique_constraint('uq_node_messages_message_id', ['message_id'])

    with op.batch_alter_table('pasture_aforos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sync_operation_receipts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'APPLIED', 'CONFLICT', 'REJECTED', name='syncoperationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.create_unique_constraint('uq_sync_operations_operation_id', ['operation_id'])

    with op.batch_alter_table('sync_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'COMPLETED', 'FAILED', name='syncsessionstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'"))
        batch_op.create_unique_constraint('uq_sync_sessions_session_id', ['session_id'])

    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('connectivity_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('NONE', 'LOW', 'INTERMITTENT', 'GOOD', name='connectivitylevel'),
               existing_nullable=False,
               existing_server_default=sa.text("'INTERMITTENT'"))

    with op.batch_alter_table('treatment_medications', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_treatment_medications_lot_id', 'inventory_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('treatment_vaccines', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_treatment_vaccines_lot_id', 'inventory_lots', ['lot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_vaccines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_treatment_vaccines_lot_id', type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('treatment_medications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_treatment_medications_lot_id', type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.alter_column('connectivity_level',
               existing_type=sa.Enum('NONE', 'LOW', 'INTERMITTENT', 'GOOD', name='connectivitylevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'INTERMITTENT'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sync_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sync_sessions_session_id', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'COMPLETED', 'FAILED', name='syncsessionstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sync_operations_operation_id', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPLIED', 'CONFLICT', 'REJECTED', name='syncoperationstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sync_operation_receipts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pasture_aforos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('node_messages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_node_messages_message_id', type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'DELIVERED', 'READ', name='nodemessagestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'"))
        batch_op.alter_column('message_type',
               existing_type=sa.Enum('CHAT', 'ALERT', 'SYSTEM', name='nodemessagetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CHAT'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('infrastructure', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('TANQUE', 'CERCA', 'MAQUINARIA', 'CORRAL', 'BEBEDERO', name='infrastructuretype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('farm_expenses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'REVOKED', 'LOST', name='devicestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('control', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('community_nodes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_community_nodes_node_id', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('attachment_blobs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attachment_blobs_attachment_id', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_animals_qr_code', type_='unique')
        batch_op.alter_column('qr_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('animal_groups', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('animal_alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_animal_alerts_field_id', type_='foreignkey')
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
