"""Add description and characteristics to species and breeds

Revision ID: 88ce4a8d3f12
Revises: 7f88764e44c7
Create Date: 2026-04-30 20:01:31.688097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ce4a8d3f12'
down_revision = '7f88764e44c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('characteristics', sa.Text(), nullable=True))

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.drop_column('characteristics')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
