"""Add Transaction model for financial module

Revision ID: bffc0a9099a9
Revises: 93a7ded129c6
Create Date: 2026-04-28 13:57:21.477855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffc0a9099a9'
down_revision = '93a7ded129c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_url')

    # ### end Alembic commands ###
