"""Initial migration with all models

Revision ID: fa2601b628e7
Revises: 
Create Date: 2026-04-27 17:34:26.770534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2601b628e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_alert_configs', schema=None) as batch_op:
        batch_op.alter_column('alert_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('REPRODUCTION', 'HEALTH', 'GROWTH', 'STATUS', 'CUSTOM', 'PREDICTIVE', name='alerttype'),
               existing_nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertpriority'),
               existing_nullable=True,
               existing_server_default=sa.text("'Alta'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_alert_configs', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Alta'"))
        batch_op.alter_column('alert_type',
               existing_type=sa.Enum('REPRODUCTION', 'HEALTH', 'GROWTH', 'STATUS', 'CUSTOM', 'PREDICTIVE', name='alerttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
